public class Params{
    
    public String FirstName{set;get;}
    public String LastName{set;get;}
    public String addOne{set;get;}
    public String addTwo{set;get;}
    public String city{set;get;}
    public String country{set;get;}
    public integer Zipcode{set;get;}
    public string email{set;get;}
    
    public integer phone{set;get;}
    
    
    
    
    public void mymethod(){
        
        // mmYY = myDate.format();
        
        
        
        
    }
    
}